# Generated by Django 4.0.4 on 2022-05-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Article',
        ),
    ]
